### ISSUE TITLE
Alternative countries

### ISSUE THREAD

**Issue by lsjmhar** [SanderKlootwijk/RadioBE#6]
Hi

Can you do versions of this app for Ireland and the UK stations?

Thanks

L

**Comment by SanderKlootwijk** [comment]
Hello!

Currently I'm working together with a German community member on a German variant of this app. If there is an UK (or Ireland) based user who would like to work on an UK variant with me, I'm in :)

If you are interested, or know someone who is, please send me an e-mail: sander.klootwijk [at] tutanota [dot] com
