### ISSUE TITLE
Adding to favorites doesn't work

### ISSUE THREAD

**Issue by Vistaus** [SanderKlootwijk/RadioBE#7]
I tried holding down anywhere on a radio station, even on the button as per the Help screen, but nothing works: the Favorites menu stays empty. This seems to me like a bug.

**Comment by SanderKlootwijk** [comment]
Thanks for reporting this issue. To make sure following the right procedure to add a station to the Favorites menu, you could try the following steps: play a radio station, open the Favorites menu, hold one of the empty buttons for a few seconds. The currently playing radio station should be added to the pressed button.

![photo_2022-11-16_20-59-40](https://user-images.githubusercontent.com/12654277/202293068-7dfa9fe6-d84c-4d95-a59c-86a60b5be24e.jpg)

**Comment by Vistaus** [comment]
Thanks. This brings to light the real issue: those button placeholders in your screenshot aren't visible with the dark theme. There's just an empty “canvas” or so to speak. But the procedure worked nonetheless. So this is something that needs to be fixed in the dark theme code.

**Comment by Vistaus** [comment]
Fixed in the latest version, mijn dank is groot!

**Comment by SanderKlootwijk** [comment]
Graag gedaan! Jij bedankt voor het melden :)
