### ISSUE TITLE
Feature Request: Klara Continuo

### ISSUE THREAD

**Issue by Vistaus** [SanderKlootwijk/RadioBE#8]
Klara is great, but it would be great if I could listen to Klara Continuo as well. :)

**Comment by SanderKlootwijk** [comment]
Thank you for your suggestion. There is now an updated version available in the OpenStore in which this station has been added.

**Comment by Vistaus** [comment]
Dank je wel, man! Alleen niet op Xenial, zo te zien. :( Het is nog altijd onduidelijk wanneer mijn Redmi 9 Focal krijgt, dus voorlopig zit ik nog aan Xenial vast.

**Comment by SanderKlootwijk** [comment]
Zelf inderdaad helemaal niet meer aan Xenial gedacht 😅

Nu moet 'ie ook voor Xenial in de store staan.

**Comment by Vistaus** [comment]
Yes, helemaal toppie - zojuist bijgewerkt! Hartelijk dank dat je nog even snel een Xenial-build hebt gepubliceerd! 🙂
